sudo: required
services:
  - docker

before_install:
  - docker build -t gfuccio92/docker-react -f Dockerfile .

script:
  - docker run -e CI=true gfuccio92/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-React"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-902754494020"
  bucket_path: "Docker-React"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY